version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11 # Specify Java version (e.g., Amazon Corretto 11)
    commands:
      - echo No dependencies to install for a simple Java app
  pre_build:
    commands:
      - echo Creating output directory...
      - mkdir -p out
  build:
    commands:
      - echo Compiling Java files...
      - javac -d out src/*.java # Compile Java files from src/ to out/ directory
  post_build:
    commands:
      - echo Running the Java application...
      - java -cp out HelloApp # Run the main class; replace `HelloApp` with your main class name
artifacts:
  files:
    - out/*.class # Include all .class files from the output directory
  discard-paths: yes
